/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;
import Logica.logicafrmNegocio;
import Negocio.Mascota;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Chuster
 */
public class Modificar extends javax.swing.JInternalFrame {
    /**
     * Creates new form Modificar
     */
    public Modificar() {
        initComponents();
        desaparecer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Modificar Datos");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Modificar Datos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 10, 187, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Digite el ID de la mascota que desea modificar sus datos:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 360, 20);

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(380, 50, 130, 30);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 90, 120, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificación", "Nombre", "Edad", "Especie", "Sexo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 160, 510, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Ingrese los nuevos datos de la Mascota");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 260, 310, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Nombre:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 350, 80, 15);

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(180, 300, 150, 30);

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(180, 340, 150, 30);

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(180, 380, 150, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Identificación:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 310, 100, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Edad:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 390, 34, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Especie");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(360, 310, 60, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "Mamífero", "Reptil", "Ave", "Anfibio", "Pez" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(430, 310, 110, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Sexo:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(360, 370, 50, 15);

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton1.setText("Macho");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(430, 360, 90, 23);

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton2.setText("Hembra");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(430, 390, 90, 23);

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(150, 430, 100, 40);

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(270, 430, 110, 40);

        jButton4.setText("Modificar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(210, 220, 130, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Datos de la Mascota:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(190, 140, 160, 17);

        pack();
    }// </editor-fold>//GEN-END:initComponents
//------------------------------------------------------------------------------
//Botón Buscar
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String id=jTextField1.getText();//Variable que obtiene el ID que digitó el usuario
        Mascota m;
        //Valida que la casilla del ID no esté vacía
        if(jTextField1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar un ID para buscar una mascoa específica...");
            limpiar();
        }
        else{
             //Obtiene el resultado (si encontró o no el ID)
             m=new logicafrmNegocio().buscarMascota(id);
             //Crea el modelo de la Tabla si encontró la Mascota en la Lista
             if(m!=null){
                 JOptionPane.showMessageDialog(null, "Se ha encontrado una mascota con ID: "+id);
                 DefaultTableModel modeloTabla=new DefaultTableModel();
                 modeloTabla.addColumn("Identificación");
                 modeloTabla.addColumn("Nombre");
                 modeloTabla.addColumn("Edad");
                 modeloTabla.addColumn("Especie");
                 modeloTabla.addColumn("Sexo");
                 //Recorre la Lista e imprime la mascota que encontró
                 Object[] datos={m.getId(),m.getNombre(),m.getEdad(),m.getEspecie(),m.getSexo()};
                 modeloTabla.addRow(datos);
                 jTable1.setModel(modeloTabla);
                 jButton4.setVisible(true);
             }
             //Si no encontró la mascota en la Lista
             else{
                 JOptionPane.showMessageDialog(null, "No se ha encontrado una mascota con ID: "+id);
                 limpiar();
                 limpiarTabla();
             }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
//------------------------------------------------------------------------------
    public void desaparecer(){
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
        jComboBox1.setVisible(false);
        jRadioButton1.setVisible(false);
        jRadioButton2.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        jButton4.setVisible(false);
    }
    //--------------------------------------------------------------------------
    public void aparecer(){
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
        jLabel7.setVisible(true);
        jLabel8.setVisible(true);
        jTextField2.setVisible(true);
        jTextField3.setVisible(true);
        jTextField4.setVisible(true);
        jComboBox1.setVisible(true);
        jRadioButton1.setVisible(true);
        jRadioButton2.setVisible(true);
        jButton2.setVisible(true);
        jButton3.setVisible(true);
    }
    //--------------------------------------------------------------------------
    //Botón Modificar
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String id=jTextField1.getText();//Variable que obtiene el ID que digitó el usuario
        Mascota m;
        //Valida que la casilla del ID no esté vacía
        if(jTextField1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar un ID para buscar una mascoa específica...");
            limpiar();
        }
        else{
            //Obtiene el resultado (si encontró o no el ID)
            m=new logicafrmNegocio().buscarMascota(id);
            //Si encontró la mascota en la Lista inicia con la solicitud de los nuevos datos
            if(m!=null){
                aparecer();
            }
            //Si no encontró la mascota en la Lista
            else{
                JOptionPane.showMessageDialog(null, "No se ha encontrado una mascota con ID: "+id);
                limpiar();
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed
//------------------------------------------------------------------------------
//Botón Cancelar
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        desaparecer();
        limpiar();
        limpiarTabla();
    }//GEN-LAST:event_jButton3ActionPerformed
//------------------------------------------------------------------------------
//Botón Guardar
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String id=jTextField1.getText();//Obtiene el ID ingresado por el usuario
        Mascota m;
        //Valida que la casilla del ID no esté vacía
        if(jTextField1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar un ID para buscar una mascoa específica...");
            limpiar();
        }
        else{
            //Valida que no hayan espacios sin completar
            if(jTextField2.getText().equals("")||jTextField3.getText().equals("")||jTextField4.getText().equals("")||jComboBox1.getSelectedItem().equals("...")||(jRadioButton1.isSelected()==false&&jRadioButton2.isSelected()==false)){
                JOptionPane.showMessageDialog(null, "No se permiten espacios en blanco...Por favor complete la información que se le solicita");
            }
            else{
                //Obtiene el resultado (si encontró o no el ID)
                m=new logicafrmNegocio().buscarMascota(id);
                //Si encontró la Mascota en la Lista
                if(m!=null){
                    //Establece los nuevos datos de la mascota
                    Mascota nueva=new Mascota();
                    nueva.setId(jTextField2.getText());
                    nueva.setNombre(jTextField3.getText());
                    nueva.setEdad(Integer.parseInt(jTextField4.getText()));
                    nueva.setEspecie(jComboBox1.getSelectedItem().toString());
                    if(jRadioButton1.isSelected()){
                        nueva.setSexo("M");
                    }
                    if(jRadioButton2.isSelected()){
                        nueva.setSexo("H"); 
                    }
                    //Llama al método modificar de la Lista con los nuevos datos ingresados
                    new logicafrmNegocio().ModificarMascota(nueva,id);
                    JOptionPane.showMessageDialog(null, "Se han guardado los cambios de manera correcta...");
                    limpiar();
                    limpiarTabla();
                    limpiarModificar();
                    desaparecer();
                }
                //Si no encontró una mascota con ID igual al que ingresó el usuario
                else{
                    JOptionPane.showMessageDialog(null, "No se ha encontrado una mascota con ID: "+id);
                    limpiar();
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        char c = evt.getKeyChar();
        if(c<'0'  || c>'9'){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Digite solamente números ");
        }//permite solo ingresar numeros
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        esconderRadios();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        esconderRadios();
    }//GEN-LAST:event_jRadioButton2ActionPerformed
//------------------------------------------------------------------------------
//Método para eliminar la Tabla
    public void limpiarTabla(){
       DefaultTableModel modeloTabla=new DefaultTableModel();
       modeloTabla.addColumn("Identificación");
       modeloTabla.addColumn("Nombre");
       modeloTabla.addColumn("Edad");
       modeloTabla.addColumn("Especie");
       modeloTabla.addColumn("Sexo");
       Object[] datos={"","","","",""};
       modeloTabla.addRow(datos);
       jTable1.setModel(modeloTabla);
    }
//------------------------------------------------------------------------------
//Método para limpiar la pantalla
    public void limpiar(){
        jTextField1.setText("");
    }
//------------------------------------------------------------------------------
//Método que limpia la pantala
    public void limpiarModificar(){
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jComboBox1.setSelectedItem("...");
        jRadioButton1.setSelected(false);
        jRadioButton1.setVisible(true);
        jRadioButton2.setSelected(false);
        jRadioButton2.setVisible(true);
    }
    //--------------------------------------------------------------------------
//Valida que solo permita elegir un RaddioButton
    public void esconderRadios(){
        if(jRadioButton1.isSelected()){
            jRadioButton2.setVisible(false);
        }
        else{
           jRadioButton2.setVisible(true); 
        }
        if(jRadioButton2.isSelected()){
            jRadioButton1.setVisible(false);
        }
        else{
            jRadioButton1.setVisible(true);
        }
    }
//------------------------------------------------------------------------------
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
